repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: uv run ruff check
        language: system
        types: [python]
        pass_filenames: false # ruff is fast enough to check everything
      - id: format
        name: format
        entry: uv run ruff format
        language: system
        types: [python]
      - id: types
        name: check types
        entry: uv run mypy
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.0.1
    hooks:
      - id: cspell # Spell check changed files
        name: check docs spelling
        files: \.(md)$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.12
    hooks:
      - id: uv-lock

default_stages: [pre-commit, pre-push]
