name: Publish to TestPyPI

on:
  workflow_dispatch:

jobs:
  publish-testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build and publish to TestPyPI
        run: |
          uv build
          uv publish --index testpypi
