name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  publish-testpypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build and publish to PyPI
        run: |
          uv build
          uv publish
